function [fname, pthname] = doc_hinh(title)
    [fname, pthname] = uigetfile( ...
        { ...
            '*.jpg'; ...
            '*.png'; ...
            '*.tiff'; ...
            '*.bmp'; ...
            '*.gif'; ...
        }, ...
        title, ...
        '*.*');
end

