function [fname, pthname] = doc_excel(title)
    [fname, pthname] = uigetfile( ...
        { ...
            '*.csv'; ...
            '*.xls'; ...
            '*.xlsx'; ...
            '*.xlsb'; ...
            '*.xlsm'; ...
        }, ...
        title, ...
        '*.xlsx');
end

