function [fname, pthname] = doc_audio(title)
    [fname, pthname] = uigetfile( ...
        { ...
            '*.mp3'; ...
            '*.mp4'; ...
            '*.wav'; ...
            '*.flac'; ...
        }, ...
        title, ...
        '*.flac');
end

