function [fname, pthname, flindex] = viet_hinh(title, toBeSaved, quality)
    switch nargin
      case 2
        quality = [];
      case 3
      otherwise
        error('3 inputs are accepted.')
    end
    [fname, pthname, flindex] = uiputfile( ...
        { ...
            '*.jpg'; ...
            '*.png'; ...
            '*.tiff'; ...
            '*.bmp'; ...
            '*.gif', ...
        }, ...
        title, ...
        '*.*');
    
    if (~isequal(fname,0) && ...
        ~isequal(pthname, 0))
        if isempty(quality)
            file = fullfile(pthname, fname);
            imwrite(toBeSaved, file);
        else
            file = fullfile(pthname, fname);
            [pathstr, name, ~] = fileparts(file);
            file = fullfile(pathstr, [name '.jpeg']);
            imwrite(toBeSaved, file, 'Quality', quality);
        end 
    end
end
